version: "3.8"
services:
  api_service:
    container_name: voomacrud
    image: willyf02/voomacrud:latest
    restart: always
    ports:
      - 8085:8085
    networks:
      - voomaapi-net
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/vooma_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${VOOMA_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${VOOMA_DB_PASSWORD}
      - BOOT_VOOMAAPI_OPENAPI_DEV_URL=${VOOMA_OPENAPI_DEV_URL}

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3308:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - voomaapi-net
    environment:
      MYSQL_DATABASE: vooma_db
      MYSQL_USER: ${VOOMA_DB_USERNAME}
      MYSQL_PASSWORD: ${VOOMA_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${VOOMA_DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysqldb", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 10
networks:
  voomaapi-net:
    name: voomaapi-net
volumes:
  mysql_data: